site_name: Pycharm Guide
site_url: https://PycharmGuide.com/
site_description: Pycharm Guide
site_author: Pycharm Guide
repo_url: https://github.com/WilsonSue/CommUserGuide.git
repo_name: Pycharm Guide
docs_dir: docs
site_dir: site
edit_uri: edit/master/docs/
nav:
  - Home: index.md
  - Adding External Library: ExternalLibrary.md
  - Adding Existing Project: ExistingProject.md
  - How to Use Debugger: Debugger.md
  - Troubleshooting: Troubleshooting.md
  - Glossary: Glossary.md

theme:
  name: material
  logo: /PyCharm_Icon.svg.png
  favicon: /PyCharm_Icon.svg.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    scheme: slate
    accent: lime
    primary: green
extra:
  homepage: https://PycharmGuide.com/
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
